# Generated by Django 3.2.4 on 2021-06-21 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('Model', models.CharField(default='', max_length=100)),
                ('Factory_Brand', models.CharField(default='', max_length=100)),
                ('Miles', models.CharField(default='', max_length=100)),
                ('Years', models.CharField(default='', max_length=100)),
                ('Colour', models.CharField(default='', max_length=100)),
                ('Ride', models.CharField(default='', max_length=100)),
                ('Engine', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/')),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mysite.car')),
            ],
        ),
    ]
